name: 💡 Feature Request
description: Suggest a new feature or enhancement for PromptTriage
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please provide as much detail as possible.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: A clear description of the problem you're facing
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: A clear description of what you want to happen
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: What other approaches did you think about?

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: Which area does this feature relate to?
      options:
        - Prompt Analysis
        - Prompt Refinement
        - UI/UX Improvements
        - API Enhancements
        - Authentication & Security
        - AI Model Integration
        - Performance
        - Documentation
        - Developer Experience
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical - Blocking my usage
        - High - Would significantly improve experience
        - Medium - Nice to have
        - Low - Minor enhancement
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your specific use case for this feature
      placeholder: How would you use this feature in your workflow?

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Examples
      description: If applicable, add mockups, examples, or references
      placeholder: Paste links, images, or examples here

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: Do you have any ideas on how this could be implemented?
      placeholder: Technical suggestions or approaches (optional)

  - type: dropdown
    id: contribution
    attributes:
      label: Would you like to contribute?
      description: Are you willing to help implement this feature?
      options:
        - Yes, I can implement this
        - Yes, I can help with testing
        - Yes, I can help with documentation
        - No, but I can provide feedback
        - Not sure
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context or information about the feature request
      placeholder: Any additional information that might be helpful

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing feature requests to avoid duplicates
          required: true
        - label: I have provided a clear description of the problem and solution
          required: true
        - label: This feature aligns with the project's goals and scope
          required: true
